### ISSUE TITLE
can not find glsl file:shader/leafStore.com.glsl and shader/mipmapNode.com.glsl

### ISSUE THREAD

**Issue by EnoroF** [otaku690/SparseVoxelOctree#1]
can not find glsl file:shader/leafStore.com.glsl and shader/mipmapNode.com.glsl when i try to run your application.

could you send it to my e-mail: EnoroF@126.com

thxs for your sharing.

**Comment by otaku690** [comment]
Sorry, forgot to commit these two files. (The mipmap compute shader is
empty now)

Thanks for the notification.

**Comment by otaku690** [comment]
Sorry, forgot to commit these two files. (Though the mipmap compute shader is empty now)

Thanks for the notification.

**Comment by HORHYSUPER** [comment]
I'll try to write a shader generation levels, but I did not get in, you could not download it?
My directx hlsl shader:

[numthreads(64, 1, 1)]
void main(uint3 dispatchThreadID : SV_DispatchThreadID)
{
	uint thxId = dispatchThreadID.x;
	if (thxId >= octreeCustomUB.numThread)
		return;

	uint node = octreeIdx[octreeCustomUB.nodeOffset + thxId];
	uint childIdx = octreeIdx[node];

	float4 color = 0;
	for (int i = 0; i < 8; i++)
		color += convRGBA8ToFloat4(octreeKd[node + i]);
	color /= 8;
	imageAtomicRGBA8Avg(color, octreeCustomUB.nodeOffset + thxId, octreeKd);
}
