### ISSUE TITLE
js implementation

### ISSUE THREAD

**Issue by ctzurcanu** [otaku690/SparseVoxelOctree#2]
Any idea what are the challenges to implement SVO in js? preferably inside an engine like voxel.js?

**Comment by otaku690** [comment]
I can think of a few: 
1. online SVO buildup: some steps rely on GLSL atomic operations.
2. 3D texture support for storing bricks: Though 3D texture could be emulated by layered texture, I have no idea what's the performance impact.

**Comment by ctzurcanu** [comment]
1. voxel.js is based on three.js that has WebGL as a preferred mode. I am not sure if this would solve the problem, but it presents hope.
2. for my particular problem, I would use just plain semi-transparent colors. I would love to octree the human body as per http://sliced.ro/smp/nav2d.php demo. (By the way: the digital model is coming from South Korea and I am in negotiations with China for their dataset for the human body)

**Comment by otaku690** [comment]
If your target is to render static scene, then precomputing the SVO on CPU is an option.
But the resulting data size might be big and require a lot of time for transferring it from server to client.
